<!doctype html>
<html lang="es">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $perfil->nombre_negocio }} | Rodante</title>@vite(['resources/css/app.css','resources/js/app.js'])<style>.seller-brand{display:flex;align-items:center;gap:12px;font:600 18px var(--display);color:var(--ink)}.seller-brand img{width:42px;height:42px;object-fit:contain}.seller-footer-brand{display:flex;align-items:center;gap:10px;font:600 17px var(--display)}.seller-footer-brand img{width:34px;height:34px;object-fit:contain}.seller-landing footer small{color:#f3aa3c;letter-spacing:1px;text-transform:uppercase;font-size:10px}.seller-intro-rich{max-width:none;display:grid;grid-template-columns:1.15fr .85fr;gap:70px;align-items:center}.intro-copy h2{font:600 clamp(38px,5vw,64px)/1 var(--display);letter-spacing:-2px;margin:0 0 22px}.intro-copy p{max-width:620px;color:var(--muted);font-size:17px;line-height:1.8}.intro-aside{border-left:1px solid var(--line);padding-left:35px;display:grid;gap:22px}.intro-stat{display:flex;align-items:center;gap:15px}.intro-stat strong{font:600 58px var(--display);color:var(--seller-primary)}.intro-stat span{font-size:11px;text-transform:uppercase;letter-spacing:1px;color:var(--muted)}.intro-detail{border-top:1px solid var(--line);padding-top:15px}.intro-detail small,.contact-panel small{display:block;color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:1px;margin-bottom:6px}.intro-detail strong,.contact-panel strong{font:500 16px var(--display)}.seller-contact-rich{display:grid;grid-template-columns:1fr 1.25fr;gap:60px;align-items:center}.contact-heading h2{font:600 clamp(34px,4vw,58px)/1 var(--display);letter-spacing:-1.5px;margin:0 0 15px}.contact-heading p{max-width:460px;color:var(--muted);line-height:1.7}.contact-panel{display:grid;grid-template-columns:1fr 1fr;gap:22px;padding:28px;background:var(--ink);color:#fff;border-radius:18px}.contact-panel small{color:#aeb8b0}.contact-panel strong{color:#fff}.contact-panel .button{grid-column:1/-1;justify-self:start;margin-top:10px}</style></head>
@php
    $sections = $perfil->secciones ?: ['hero','intro','inventario','contacto','footer'];
    $landingTitle = $perfil->titulo_portada ?: $perfil->nombre_negocio;
    $landingSubtitle = $perfil->subtitulo_portada ?: ($perfil->descripcion ?: 'Vehículos seleccionados para acompañar tu próximo destino.');
@endphp
<style>
.seller-landing{background:#f7f5f0;color:#17211f}.seller-landing .seller-nav{background:rgba(247,245,240,.9);border-bottom:1px solid #dedbd2}.seller-landing .seller-nav nav{gap:30px}.seller-landing .seller-nav nav a{font-size:12px;text-transform:uppercase;letter-spacing:1px}.seller-landing .seller-hero{min-height:680px}.seller-landing .seller-hero-content{max-width:760px;padding-top:clamp(90px,12vw,150px)}.seller-landing .seller-hero-content h1{max-width:700px;font-size:clamp(48px,7vw,100px)}.seller-landing .seller-intro-rich{min-height:460px;padding-top:120px;padding-bottom:120px;background:#fff}.seller-landing .seller-inventory{background:#ece9e1;padding-top:110px;padding-bottom:120px}.seller-landing .seller-inventory .section-heading{max-width:1200px;margin-left:auto;margin-right:auto}.seller-landing .seller-inventory .vehicle-grid{max-width:1200px;margin:0 auto}.seller-landing .seller-contact-rich{padding:110px 10vw;min-height:450px;background:var(--seller-primary);color:#fff}.seller-landing .contact-heading .eyebrow{color:var(--seller-secondary)}.seller-landing .contact-heading h2{max-width:660px}.seller-landing .contact-heading p{color:rgba(255,255,255,.72)}.seller-landing .contact-panel{background:rgba(0,0,0,.22);border:1px solid rgba(255,255,255,.2);box-shadow:none}.seller-landing .contact-panel small{color:rgba(255,255,255,.6)}.seller-landing .contact-panel strong{font-size:18px}.seller-landing footer{min-height:130px;padding:35px 10vw;align-items:center}.seller-landing footer p{margin-left:auto;margin-right:60px}@media(max-width:950px){.seller-landing .seller-nav{flex-wrap:wrap;padding:14px 20px}.seller-landing .seller-nav nav{width:100%;justify-content:center;flex-wrap:wrap;gap:12px}.seller-landing .seller-hero{grid-template-columns:1fr;min-height:520px}.seller-landing .seller-hero-content{padding:70px 20px 40px}.seller-landing .seller-intro-rich,.seller-landing .seller-contact-rich{grid-template-columns:1fr;gap:28px}.seller-landing .intro-aside{border-left:0;border-top:1px solid var(--line);padding-left:0;padding-top:22px}.seller-landing .contact-panel{grid-template-columns:1fr;padding:22px}.seller-landing footer{display:flex;flex-wrap:wrap;gap:16px;padding:28px 20px}.seller-landing footer p{margin:0}}@media(max-width:750px){.seller-landing .seller-nav nav{gap:14px}.seller-landing .seller-nav nav a{font-size:10px}.seller-landing .seller-hero{min-height:580px}.seller-landing .seller-intro-rich{padding-top:70px;padding-bottom:70px}.seller-landing .seller-inventory{padding-top:70px;padding-bottom:75px}.seller-landing .seller-contact-rich{padding:70px 20px}.seller-landing footer{display:flex;flex-wrap:wrap;gap:16px;padding:28px 20px}.seller-landing footer p{margin:0 0 0 auto}.seller-landing footer small{width:100%}.seller-landing .seller-brand{font-size:15px}} 
</style>
<style>@media(max-width:950px){.seller-intro-rich,.seller-contact-rich{display:grid}.intro-aside{border-left:0;border-top:1px solid var(--line);padding:22px 0 0;margin-top:28px}.contact-panel{margin-top:28px;grid-template-columns:1fr;padding:22px}.contact-panel .button{grid-column:auto}.intro-copy h2,.contact-heading h2{letter-spacing:-1px}}@media(max-width:750px){.seller-intro-rich,.seller-contact-rich{display:block}.intro-aside{border-left:0;border-top:1px solid var(--line);padding:24px 0 0;margin-top:28px}.contact-panel{margin-top:28px;grid-template-columns:1fr;padding:22px}.contact-panel .button{grid-column:auto}.intro-copy h2,.contact-heading h2{letter-spacing:-1px}}</style>
<body class="seller-landing template-{{ $perfil->plantilla ?: 'editorial' }}" data-seller-primary="{{ $perfil->color_principal }}" data-seller-secondary="{{ $perfil->color_secundario }}">
<header class="seller-nav"><a class="seller-brand" href="#inicio" aria-label="Inicio de {{ $perfil->nombre_negocio }}">@if($perfil->logo)<img src="{{ asset('storage/' . $perfil->logo) }}" alt="Logo de {{ $perfil->nombre_negocio }}">@else<strong>{{ $perfil->nombre_negocio }}</strong>@endif</a><nav>@if(in_array('intro',$sections,true))<a href="#sobre-nosotros">Nosotros</a>@endif @if(in_array('inventario',$sections,true))<a href="#inventario">Inventario</a>@endif @if(in_array('contacto',$sections,true))<a href="#contacto">Contacto</a>@endif</nav></header>
<main id="inicio">
@foreach($sections as $section)
    @includeIf('vendedor.sections.' . $section)
@endforeach
</main>
</body>
</html>